### ISSUE TITLE
Focus more on career goals

### ISSUE THREAD

**Issue by jnnjogu** [jnnjogu/BioinformaticsJourney#2]
Speak more on how you want to get there @jnnjogu @fnyasimi

**Comment by jnnjogu** [comment]
Acting on it @jnnjogu @fnyasimi

**Comment by Fnyasimi** [comment]
@jnnjogu looks good, use informative headers for your issues and pull requests. You can merge the pull request

**Comment by jnnjogu** [comment]
@Fnyasimi Noted
